In [118]:
import pandas as pd   
import matplotlib.pyplot as plt  
from datetime import timedelta, time
import seaborn as sns 
import datetime 
import pytz
#from datetime import time

In [119]:
df = pd.read_csv('c:/Users/Admin/lesson2/Scripts/innogrowsensors.csv', parse_dates = ['Ts'], dayfirst = False)  
#print(df)
gap = timedelta(seconds = 30)

In [120]:
df_new = df[['Contents.Main tank 100% [bool]', 'Contents.Main tank 85% [bool]','Contents.Main tank 30% [bool]',  'Contents.Main tank 5% [bool]', 'Ts']] 
df_new_sorted = df_new.sort_values(by = 'Ts', ascending = True) 

begin_index = 270000
df_time_index = df_new_sorted.set_index('Ts') 
df_slice = df_time_index[begin_index : begin_index + 55000]
#print(df_slice)

In [121]:
mt100 = [ df_new_sorted.loc[begin_index,  'Contents.Main tank 100% [bool]' ] ]
mt85 = [ df_new_sorted.loc[begin_index,  'Contents.Main tank 85% [bool]'] ]
mt30 = [ df_new_sorted.loc[begin_index,  'Contents.Main tank 30% [bool]'] ]
mt5 = [ df_new_sorted.loc[begin_index,  'Contents.Main tank 5% [bool]'] ]
time_arr =  [datetime.datetime(2022, 12, 21, 10, 18, 49, 0, tzinfo=pytz.utc)] 
#time_arr[-1]
#time_st1 = time_st.to_pydatetime()

In [122]:
max_index = 55000 - 1
max_time = df_slice.index[max_index]

In [123]:
cur_time = time_arr[0] 
index_in_old = 0 
#gg = df_new_sorted.loc[begin_index + index_in_old, 'Ts']
#print(gg)
# if min(df_new_sorted.loc[begin_index + index_in_old, 'Ts'] - cur_time, cur_time - df_new_sorted.loc[begin_index + index_in_old - 1], 'Ts') < gap/2:

In [124]:
cur_time = time_arr[-1]
#print(cur_time)
#print(max_time)

#new_max = datetime.datetime(2022, 12, 22, 10, 18, 49, 0, tzinfo=pytz.utc)
#while cur_time < new_max: 
while cur_time < max_time: 
    cur_time += gap
    # пока сurrent_time больше времени, которое мы получаем по индексу index_in_old 
    #print('ct ', cur_time)
    #print('oth ', df_new_sorted.loc[begin_index + index_in_old, 'Ts'])
    while cur_time > df_new_sorted.loc[begin_index + index_in_old, 'Ts']: 
        index_in_old += 1
    #print('iod', index_in_old)
    before = cur_time - df_new_sorted.loc[begin_index + index_in_old - 1, 'Ts']
    after = df_new_sorted.loc[begin_index + index_in_old, 'Ts'] - cur_time
    #print(k)
    if ((min(before, after) >= 0.5*gap) and (max(before, after) <= 1.5*gap)): 
        if df_new_sorted.loc[begin_index + index_in_old, 'Ts'] - cur_time <= cur_time - df_new_sorted.loc[begin_index + index_in_old - 1, 'Ts']:
            mt100.append(df_new_sorted.loc[begin_index + index_in_old, 'Contents.Main tank 100% [bool]'] )
            mt85.append(df_new_sorted.loc[begin_index + index_in_old, 'Contents.Main tank 85% [bool]'] ) 
            mt30.append(df_new_sorted.loc[begin_index + index_in_old, 'Contents.Main tank 30% [bool]'] )
            mt5.append(df_new_sorted.loc[begin_index + index_in_old, 'Contents.Main tank 5% [bool]'] )
            time_arr.append(cur_time)                  
        else:
            mt100.append(df_new_sorted.loc[begin_index + index_in_old - 1, 'Contents.Main tank 100% [bool]'] )
            mt85.append(df_new_sorted.loc[begin_index + index_in_old - 1 , 'Contents.Main tank 85% [bool]'] )
            mt30.append(df_new_sorted.loc[begin_index + index_in_old - 1, 'Contents.Main tank 30% [bool]'] )
            mt5.append(df_new_sorted.loc[begin_index + index_in_old - 1, 'Contents.Main tank 5% [bool]'] )
            time_arr.append(cur_time) 
    elif ((min(before, after) < 0.5*gap) and (0.5*gap <=  max(before, after) <= 1.5*gap)):
        if (min(before, after) == before): # Тогда берем значения из after
            mt100.append(df_new_sorted.loc[begin_index + index_in_old, 'Contents.Main tank 100% [bool]'] )
            mt85.append(df_new_sorted.loc[begin_index + index_in_old, 'Contents.Main tank 85% [bool]'] ) 
            mt30.append(df_new_sorted.loc[begin_index + index_in_old, 'Contents.Main tank 30% [bool]'] )
            mt5.append(df_new_sorted.loc[begin_index + index_in_old, 'Contents.Main tank 5% [bool]'] )
            time_arr.append(cur_time) 
        else:
            mt100.append(df_new_sorted.loc[begin_index + index_in_old - 1, 'Contents.Main tank 100% [bool]'] )
            mt85.append(df_new_sorted.loc[begin_index + index_in_old - 1 , 'Contents.Main tank 85% [bool]'] )
            mt30.append(df_new_sorted.loc[begin_index + index_in_old - 1, 'Contents.Main tank 30% [bool]'] )
            mt5.append(df_new_sorted.loc[begin_index + index_in_old - 1, 'Contents.Main tank 5% [bool]'] )
            time_arr.append(cur_time)
    elif ((max(before, after) > 1.5*gap) and (0.5*gap <= min(before, after) <= 1.5*gap)):
        if (max(before, after) == before): # Тогда берем значения из after
            mt100.append(df_new_sorted.loc[begin_index + index_in_old, 'Contents.Main tank 100% [bool]'] )
            mt85.append(df_new_sorted.loc[begin_index + index_in_old, 'Contents.Main tank 85% [bool]'] ) 
            mt30.append(df_new_sorted.loc[begin_index + index_in_old, 'Contents.Main tank 30% [bool]'] )
            mt5.append(df_new_sorted.loc[begin_index + index_in_old, 'Contents.Main tank 5% [bool]'] )
            time_arr.append(cur_time) 
        else:
            mt100.append(df_new_sorted.loc[begin_index + index_in_old - 1, 'Contents.Main tank 100% [bool]'] )
            mt85.append(df_new_sorted.loc[begin_index + index_in_old - 1 , 'Contents.Main tank 85% [bool]'] )
            mt30.append(df_new_sorted.loc[begin_index + index_in_old - 1, 'Contents.Main tank 30% [bool]'] )
            mt5.append(df_new_sorted.loc[begin_index + index_in_old - 1, 'Contents.Main tank 5% [bool]'] )
            time_arr.append(cur_time)     
    else: # добавляем в список cur_time и заполняем все (-1)
        mt100.append(-1)
        mt85.append(-1)
        mt30.append(-1)
        mt5.append(-1)
        time_arr.append(cur_time)   
        #print(df_new_sorted.loc[begin_index + index_in_old - 1, 'Ts'])
        #print(cur_time)
        #print(df_new_sorted.loc[begin_index + index_in_old, 'Ts'])
        #print(before)
        #print(after)
        #print('  ')
        

#for i in range(1, len(time_arr)):
    #if mt100[i] == -1:
        #print(mt100[i], time_arr[i])
#print(len(time_arr))

In [126]:
result = pd.DataFrame({ "Time": time_arr, "MT100": mt100, "MT85": mt85, "MT30": mt30, "MT5": mt5 })
result.to_csv("resampled.csv")
result

                            Time  MT100  MT85  MT30  MT5
0      2022-12-21 10:18:49+00:00      0   1.0     1    1
1      2022-12-21 10:19:19+00:00      0   1.0     1    1
2      2022-12-21 10:19:49+00:00      0   1.0     1    1
3      2022-12-21 10:20:19+00:00      0   1.0     1    1
4      2022-12-21 10:20:49+00:00      0   1.0     1    1
...                          ...    ...   ...   ...  ...
140897 2023-02-08 08:27:19+00:00      0   1.0     1    1
140898 2023-02-08 08:27:49+00:00     -1  -1.0    -1   -1
140899 2023-02-08 08:28:19+00:00      0   1.0     1    1
140900 2023-02-08 08:28:49+00:00     -1  -1.0    -1   -1
140901 2023-02-08 08:29:19+00:00     -1  -1.0    -1   -1

[140902 rows x 5 columns]